apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
  - image: ui
    context: ui
    docker:
      dockerfile: Dockerfile
    sync:
      infer:
        - 'src/build/*.*'
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
    - ./kubernetes-manifests/**/**.yaml
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: dockerfile
  build:
    artifacts:
    - image: ui
      context: ui
      sync:
        infer:
          - 'src/build/*.*'
