apiVersion:   v1
name:         reconciliation-tester
description:  Recon front end to test Recon. The app itself is nuxt and is in REC/isb-recon-fe
type:         application
version:      0.1.0
appVersion:   "0.0.2"
