apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: gap
  labels:
    app: ui
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: ui
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
