apiVersion: v1
kind: Service
metadata:
  name: book-checkout
  namespace: gap
  labels:
    app: book-checkout
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: book-checkout
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
