{{- if not .Values.app.vaultSecrets.mongo }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reconciliation.fullname" . }}
  labels:
    {{- include "reconciliation.labels" . | nindent 4 }}
stringData:
  {{- with .Values.app.mongo }}
  mongoDsn: {{ .prefix }}{{ .username }}:{{ .password }}@{{ .host }}/{{ .database }}?{{ .options }}
  {{- end }}
{{- end }}
