apiVersion: v1
kind: Service
metadata:
  name: {{ include "reconciliation.fullname" . }}
  labels:
    {{- include "reconciliation.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: node
      protocol: TCP
      name: node
  selector:
    {{- include "reconciliation.selectorLabels" . | nindent 4 }}
