apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: gap
  labels:
    app: discovery-service
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: discovery-service
    tier: frontend
  ports:
    - port: 8761
      name: discovery-service
